feat: format files output message
trzsz/trzsz-go pull request #32
Opened 2023-06-05 07:02 UTC by amo996

Format the file output message, the effect is as follows：
Received 3 files to /root:
- 1. Xnip2023-05-15_19-07-42.jpg
- 2. Xnip2023-05-15_19-09-00.jpg
- 3. Xnip2023-05-15_19-14-33.jpg

2023-06-05 08:01 UTC, lonnywong commented
@amo996 太感谢了，还有这里也要改一下：https://github.com/trzsz/trzsz-go/blob/1e5952402811a4918883efbeb8dec8161295fc07/trzsz/filter.go#L259

2023-06-05 08:41 UTC, amo996 commented
> @amo996 太感谢了，还有这里也要改一下：
> 
> https://github.com/trzsz/trzsz-go/blob/1e5952402811a4918883efbeb8dec8161295fc07/trzsz/filter.go#L259

改好了

2023-06-05 08:57 UTC, lonnywong commented
@amo996 git commit 时，注意用 github 的邮箱，要不关联不出贡献者来。改好后，可以 git rebase 一下，整成一个 commit 。

2023-06-05 09:47 UTC, amo996 commented
> @amo996 git commit 时，注意用 github 的邮箱，要不关联不出贡献者来。改好后，可以 git rebase 一下，整成一个 commit 。

改好了，现在可以了吗

2023-06-05 10:34 UTC, lonnywong commented
> 改好了，现在可以了吗

前面提的那些 review 意见，改一下？

2023-06-06 05:50 UTC, lonnywong requested changes

2023-06-07 14:50 UTC, merged